config/routes.rb
Rails.application.routes.draw do
  resources :sells
  get 'terms/terminosycondiciones'
  get 'about/aboutus'
  resources :contacts, only: [:new, :create, :index, :show]
  resources :publications
  resources :products
  resources :clients
  devise_for :users, controllers: {
  sessions: 'users/sessions'
  }

  get "contacts/export_data", to: "contacts#export", as: :export_contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :product
  belongs_to :user
  has_many :clients, through: :product
  has_many :contacts, dependent: :destroy
  has_many_attached :images
  

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action :authenticate_admin, only: %i[new create edit update destroy]

  include Pagy::Backend

  # GET /publications or /publications.json
  def index

    @publications = Publication.all
    @pagy, @publications = pagy(Publication.order(created_at: :desc), items: 3)
  end

  # GET /publications/1 or /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    @contact = Contact.new # Esto inicializa un nuevo objeto Contact vacío para el formulario
  end

  # GET /publications/new
  def new
    @publication = Publication.new
    @products = Product.includes(:client).order(created_at: :desc)
    @clients = Client.all.map { |client| ["#{client.name} #{client.lastName}", client.id] }

  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.new
    @products = Product.includes(:client).order(created_at: :desc)
    @clients = Client.all.map { |client| ["#{client.name} #{client.lastName}", client.id] }
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id
    @products = Product.all
    @clients = Client.all.map { |client| ["#{client.name} #{client.lastName}", client.id] }

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:description, :product_id, :user_id, images: [])
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
<% if publication.errors.any? %>
<div style="color: red">
  <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

  <ul>
    <% publication.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :images, 'Subir imágenes' %>
  <%= form.file_field :images, multiple: true %>
</div>

<div>
  <%= form.label :descripción, style: "display: block" %>
  <%= form.text_area :description %>
</div>

<div>
  <%= form.label :producto, style: "display: block" %>
  <%= form.collection_select :product_id, @products, :id, lambda { |product| "#{product.client.name} #{product.client.lastName}" }, prompt: "Selecciona un producto" %>
</div>

<div>
  <%= form.label :usuario, style: "display: block" %>
  <%= form.collection_select :user_id, @clients, :second, :first, prompt: "Cliente" %>
</div>

<div>
  <%= form.submit "Subir publicación" %>
</div>
<% end %>

app/views/publications/_publication.html.erb
<div class="container">
  <div class="card">
    <div id="imageCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% if publication.images.attached? %>
        <% publication.images.each_with_index do |image, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <%= image_tag image, class: "d-block w-80" %>
        </div>
        <% end %>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#imageCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#imageCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="card-body">
      <strong>Description:</strong>
      <%= publication.description %>
      <p>
        <strong>Product:</strong>
        <%= publication.product_id %>
      </p>
      <p>
        <strong>User:</strong>
        <%= publication.user_id %>
      </p>
    </div>
  </div>
</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<div class="sell">
  <div class="background-overlay">

    <h1 class="text-with-shadow">VENDE CON NOSOTROS</h1>

    <%= link_to "Contactar", new_sell_path, class: "btn btn-light btn-contact" %>

  </div>
</div>
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%if user_signed_in? && current_user.role == "admin"%>
  <%= link_to "Nueva publicación", new_publication_path, class: "btn btn-outline-secondary", style: "margin-bottom: 20px;" %>
  <%end%>

  <h1>Últimos productos</h1>

  <div class="row">
    <% @publications.each do |publication| %>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <div class="publication-card">
        <div id="imageCarousel<%= publication.id %>" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <% if publication.images.attached? %>
            <% publication.images.each_with_index do |image, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
              <%= image_tag image, style: "width: 900px; height: 500px; display: block; margin: 0 auto;" %>
            </div>
            <% end %>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#imageCarousel<%= publication.id %>" role="button"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </a>
          <a class="carousel-control-next" href="#imageCarousel<%= publication.id %>" role="button"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </a>
        </div>
        <br />
        <table>
          <tr>
            <th>Tipo:</th>
            <td><%= publication.product.type.name %></td>
          </tr>
          <tr>
            <th>Composición:</th>
            <td><%= publication.product.composition.name %></td>
          </tr>
          <tr>
            <th>Localidad:</th>
            <td><%= publication.product.client.locality.name %></td>
          </tr>
          <tr>
            <th>Cantidad:</th>
            <td><%= publication.product.quantity %></td>
          </tr>
        </table>
        <p>
          <%= link_to "Ver producto", publication, class: "btn btn-outline-secondary", style:"margin-top:10px;"%>
        </p>
      </div>
    </div>
    <% end %>
  </div>
  <%== pagy_nav(@pagy) %>
</div>

app/views/publications/new.html.erb
<div class="container">
<h1>Nueva publicación</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Volver", publications_path %>
</div>
</div>

app/views/publications/show.html.erb
<div class="container pt-3" style="color:white;">
  <div class="col-sm-12">
    <p style="color: green"><%= notice %></p>
    <div id="imageCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% if @publication.images.attached? %>
        <% @publication.images.each_with_index do |image, index| %>
        <div class="carousel-item custom-carousel-item <%= 'active' if index == 0 %>">
          <%= image_tag image, class: "d-block w-100 img-fluid" %>
        </div>
        <% end %>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#imageCarousel" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </a>
      <a class="carousel-control-next" href="#imageCarousel" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </a>
    </div>
    <br />

    <div class="card" id="card-show">
      <table class="table">
        <tbody id="table-show">
          <tr>
            <th scope="row">Descripción</th>
            <td><%= @publication.description %></td>
          </tr>
          <tr>
            <th scope="row">Tipo</th>
            <td><%= @publication.product.type.name %></td>
          </tr>
          <tr>
            <th scope="row">Composición</th>
            <td><%= @publication.product.composition.name %></td>
          </tr>
          <tr>
            <th scope="row">Localidad</th>
            <td><%= @publication.product.client.locality.name %></td>
          </tr>
          <tr>
            <th scope="row">Cantidad</th>
            <td><%= @publication.product.quantity %> </td>
          </tr>
          <tr>
            <th scope="row">Informe</th>
            <td>
              <ul class="list-unstyled">
                <% if @publication.product.files.any? %>
                <ul class="list-unstyled">
                  <% @publication.product.files.each do |file| %>
                  <li>
                    <%= link_to file.filename, rails_blob_path(file, disposition: "attachment") %>
                  </li>
                  <% end %>
                </ul>
                <% else %>
                <li>No hay informe disponible.</li>
                <% end %>
              </ul>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="botons">
      <%if user_signed_in? && current_user.role == "admin"%>
      <%= link_to "Editar publicación", edit_publication_path(@publication), class: "btn btn-outline-secondary",style:"margin-top: 10px;" %>
      <%= button_to "Eliminar", @publication, method: :delete, class: "btn btn-outline-secondary", style: "margin-top: 10px;" %>
      <%end%>
      <%= link_to "Volver", publications_path, class: "btn btn-outline-secondary", style:"margin-top: 10px;" %>
    </div>
    <hr>
    <br />
    <div class="titulo">
      <h2>Cotiza!</h2>
      <h3>Uno de nuestros ejecutivos se contactará usted </p>
    </div>
    <%= render 'contacts/contact_form', contact: Contact.new(publication_id: @publication.id) %>

  </div>
</div>