config/routes.rb
Rails.application.routes.draw do
  resources :sells
  get 'terms/terminosycondiciones'
  get 'about/aboutus'
  resources :contacts, only: [:new, :create, :index, :show]
  resources :publications
  resources :products
  resources :clients
  devise_for :users, controllers: {
  sessions: 'users/sessions'
  }

  get "contacts/export_data", to: "contacts#export", as: :export_contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :locality
  has_many :products
end

app/models/composition.rb
class Composition < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :locality
  belongs_to :publication
end

app/models/locality.rb
class Locality < ApplicationRecord
    has_many :publications
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :type
  belongs_to :composition
  belongs_to :locality
  belongs_to :client
  has_many_attached :files
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :product
  belongs_to :user
  has_many :clients, through: :product
  has_many :contacts, dependent: :destroy
  has_many_attached :images
  

end

app/models/sell.rb
class Sell < ApplicationRecord
  belongs_to :locality
end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         enum role: [:normal_user, :admin]
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def aboutus
  end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  before_action :set_sell, only: %i[ show edit update destroy ]

  # GET /sells or /sells.json
  def index
    @sells = Sell.all
  end

  # GET /sells/1 or /sells/1.json
  def show
  end

  # GET /sells/new
  def new
    @sell = Sell.new
  end

  # GET /sells/1/edit
  def edit
  end

  # POST /sells or /sells.json
  def create
    @sell = Sell.new(sell_params)

    respond_to do |format|
      if @sell.save
        format.html { redirect_to sell_url(@sell), notice: "Sell was successfully created." }
        format.json { render :show, status: :created, location: @sell }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sells/1 or /sells/1.json
  def update
    respond_to do |format|
      if @sell.update(sell_params)
        format.html { redirect_to sell_url(@sell), notice: "Sell was successfully updated." }
        format.json { render :show, status: :ok, location: @sell }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sells/1 or /sells/1.json
  def destroy
    @sell.destroy

    respond_to do |format|
      format.html { redirect_to sells_url, notice: "Sell was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sell
      @sell = Sell.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sell_params
      params.require(:sell).permit(:name, :lastName, :phone, :email, :content, :locality_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    include Pagy::Frontend


end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Nueva esperanza</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;1,100&display=swap">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="body">
  <nav class="navbar navbar-expand-lg bg-body-tertiary mi-navbar">
    <div class="container-fluid">
      <%= link_to(image_tag("logoblanco.png", style: "width: 250px;"), publications_path, class: "navbar-brand") %>
      <%= link_to "whatsapp://send?phone=56976345068", class: "btn btn-link btn-floating btn-lg text-white m-1", role: "button", target: "_blank", style: "font-family: 'Roboto', sans-serif;" do %>
      <i class="fab fa-whatsapp fa-3x" style="padding-right:30px;"></i>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Mercado", publications_path, class:"nav-link active text-white" %>
          </li>
          <% if user_signed_in? && current_user.role == "admin" %>
          <li class="nav-item">
            <%= link_to "Productos", products_path, class:"nav-link active text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Clientes", clients_path, class:"nav-link active text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Compra", contacts_path, class:"nav-link active text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Ventas", sells_path, class:"nav-link active text-white" %>
          </li>
          <% end %>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Cerrar sesión", destroy_user_session_path, class:"nav-link active text-white" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Iniciar sesión", new_user_session_path, class:"nav-link active text-white" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="yeld">
    <%= yield %>
  </div>

  <footer class="text-center text-white" style="background-color: #20264B;">
    <div class="container pt-4">
      <section class="mb-4">
        <!-- Redes sociales -->
        <a class="btn btn-link btn-floating btn-lg text-white m-1" href="#!" role="button"><i
            class="fab fa-facebook-f"></i></a>
        <a class="btn btn-link btn-floating btn-lg text-white m-1" href="#!" role="button"><i
            class="fab fa-twitter"></i></a>
        <a class="btn btn-link btn-floating btn-lg text-white m-1" href="#!" role="button"><i
            class="fab fa-whatsapp"></i></a>
        <a class="btn btn-link btn-floating btn-lg text-white m-1" href="#!" role="button"><i
            class="fab fa-instagram"></i></a>
        <a class="btn btn-link btn-floating btn-lg text-white m-1" href="#!" role="button"><i
            class="fab fa-linkedin"></i></a>
      </section>
    </div>

    <div class="text-bottom text-white p-3 custom-foot" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 Derechos reservados: <%= image_tag "logoblanco.png", style: "width: 150px;" %>
      <p><%= link_to "Terminos y Condiciones", terms_terminosycondiciones_path %></p>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
  </script>
</body>

</html>